name: automatic-dropbox-uploader
on:
  push:
    branches: [main]

jobs:
  package:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm run test #build here, etc
      - uses: papeloto/action-zip@v1
        with:
          files: test.txt
          dest: package.zip

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: package.zip
  dropbox:
    needs: [package]
    runs-on: ubuntu-18.04
    steps:
      - name: Upload
        uses: actions/download-artifact@v2
        with:
          name: package
      - name: Dropbox
        uses: aTable/deploy-to-dropbox@v1.0.7
        with:
          DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          DROPBOX_DESTINATION_PATH_PREFIX: "/"
          GLOB: "package.zip"
          DEBUG: false
