name: automatic-dropbox-uploader
on:
  push:
    branches: [main]

jobs:
  package:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
            node-version: 14.x
      - run: npm run test #build here, etc
      - uses: papeloto/action-zip@v1
        with:
          files: test.txt
          dest: package.zip

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
            name: package
            path: ./package.zip        
  dropbox:
    runs-on: ubuntu-18.04
      steps:
        - name: Upload
          uses: actions/download-artifact@v2
          with:
              name: package
        - name: Dropbox
          uses: whalemare/action-dropbox@v1.0.0
          with:
            file: "package.zip"
            acessToken: "sl.BDgWa_7u77BWI2YqiYOGEB6cXX5WsTn5x9qpWrgu_-ZD729iuFjorTOjBeDDIL5cqoM1HB9BNdTX1abs_JXhMICwhN0-eZHqWJaJgfJyOkTZwq4rM01loThFqHfydz4UdZDbZyI"
            destination: "my-dir" 
      
